version: '3.7'

services:
  testacesso-db:
    image: mcr.microsoft.com/mssql/server
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "P4ss-W0rd!"
    ports:
      - 1433:1433
    volumes:
      - sqldata:/var/opt/mssql/data
    networks:
      - testacesso-network

  testacesso-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      - testacesso-network    

  baldini-testacesso:
    image: baldini/testacesso
    ports:
      - 5000:80
    networks:
      - testacesso-network    

  testacesso-webapi:
    image: testacesso-webapi
    build:
      context: .
      dockerfile: TestAcesso.Webapi/Dockerfile
    env_file:
      - env/services.env
      - env/rabbitmq.env
    environment:
      CONN: "Server=testacesso-db,1433;Initial Catalog=master;User ID=sa;Password=P4ss-W0rd!;"
    ports:
      - 54217:80
    depends_on:
      - testacesso-db
      - baldini-testacesso
    networks:
      - testacesso-network

  

volumes:
  sqldata:
  rabbitdata:

networks:
  testacesso-network: